<a href="https://colab.research.google.com/github/MathewBiddle/sandbox/blob/main/notebooks/check_doi_status.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import json
import pandas as pd

In [ ]:
dois = [ '10.1371/journal.pone.0302497',
       '10.1016/j.dsr2.2024.105380',
       '10.1016/j.dsr2.2023.105335',
       '10.1016/j.marpolbul.2023.115840',
       '10.1016/j.dsr2.2023.105344',
       '10.1016/j.dsr2.2023.105321',
       '10.1111/fog.12655',
       '10.1578/am.49.6.2023.519',
       '10.1016/j.dsr2.2023.105322',
       '10.1016/j.dsr2.2023.105346',
       '10.1016/j.dsr2.2023.105341',
       '10.1126/sciadv.adl3169',
       '10.1007/s10236-024-01605-y',
       '10.1016/j.pocean.2024.103244',
       '10.1029/2024JC020993',
       '10.1016/j.pocean.2024.103263',
       '10.1016/j.coastaleng.2024.104617',
       '10.1016/j.eti.2024.103676',
       '10.1007/s10236-024-01608-9',
       '10.1016/j.dsr2.2024.105395',
       '10.3389/fmars.2024.1387180',
       '10.3389/fevo.2023.1288596',
       '10.1016/j.hal.2023.102522',
]

In [ ]:
base_url = "https://api.unpaywall.org/v2/doi/"

df = pd.DataFrame({'doi': dois})

for doi in df['doi']:

  url = f'{base_url}{doi}?email=someone@somewhere.com'

  try:
      response = requests.get(url)
      response.raise_for_status()  # Raise an exception for bad status codes
      data = response.json()
      open = data['is_oa']
      df.loc[df['doi']==doi,'Open'] = open
  except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")

In [ ]:
df.loc[df['Open']==False,'doi']

1       10.1016/j.dsr2.2024.105380
2       10.1016/j.dsr2.2023.105335
5       10.1016/j.dsr2.2023.105321
8       10.1016/j.dsr2.2023.105322
9       10.1016/j.dsr2.2023.105346
10      10.1016/j.dsr2.2023.105341
13    10.1016/j.pocean.2024.103244
14            10.1029/2024JC020993
15    10.1016/j.pocean.2024.103263
18      10.1007/s10236-024-01608-9
19      10.1016/j.dsr2.2024.105395
Name: doi, dtype: object

In [ ]:
df

                                 doi   Open
0       10.1371/journal.pone.0302497   True
1         10.1016/j.dsr2.2024.105380  False
2         10.1016/j.dsr2.2023.105335  False
3    10.1016/j.marpolbul.2023.115840   True
4         10.1016/j.dsr2.2023.105344   True
5         10.1016/j.dsr2.2023.105321  False
6                  10.1111/fog.12655   True
7           10.1578/am.49.6.2023.519   True
8         10.1016/j.dsr2.2023.105322  False
9         10.1016/j.dsr2.2023.105346  False
10        10.1016/j.dsr2.2023.105341  False
11            10.1126/sciadv.adl3169   True
12        10.1007/s10236-024-01605-y   True
13      10.1016/j.pocean.2024.103244  False
14              10.1029/2024JC020993  False
15      10.1016/j.pocean.2024.103263  False
16  10.1016/j.coastaleng.2024.104617   True
17         10.1016/j.eti.2024.103676   True
18        10.1007/s10236-024-01608-9  False
19        10.1016/j.dsr2.2024.105395  False
20        10.3389/fmars.2024.1387180   True
21         10.3389/fevo.2023.1288596   True
22         10.1016/j.hal.2023.102522   True